
---
resources:
- name: service-core
  type: git
  source:
    uri: https://github.com/kbastani/service-block-samples
    branch: master
    paths:
    - ./todo-block/github-event-core
- name: commit-metrics
  type: git
  source:
    uri: https://github.com/kbastani/service-block-samples
    branch: master
    paths:
    - ./todo-block/functions/commit-metrics
jobs:
- name: github-todo-block
  max_in_flight: 1
  plan:
  - get: service-core
    trigger: true
  - task: build
    file: service-core/todo-block/deployment/tasks/build-core.yml
  - task: deployment
    file: service-core/todo-block/deployment/tasks/deploy-core.yml
    params:
      path: artifact/github-event-core.jar
      current_app_name: github-event-core
      host: github-event-core
      domain: cfapps.io
      manifest: service-core/todo-block/github-event-core/manifest.yml
      api: {{pws-api}}
      username: {{pws-username}}
      password: {{pws-password}}
      organization: {{pws-org}}
      aws_access_key_id: {{aws-access-key-id}}
      aws_access_key_secret: {{aws-access-key-secret}}
      github_access_token: {{github-access-token}}
      space: {{pws-space}}
- name: commit-metrics
  max_in_flight: 1
  plan:
  - get: commit-metrics
    trigger: true
  - task: prepare
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
        - name: commit-metrics
      outputs:
        - name: functions
        - name: scripts
      run:
        path: sh
        args:
        - -exc
        - |
          cp -r commit-metrics/todo-block/functions/* functions \
          && cp -r commit-metrics/todo-block/deployment/scripts/* scripts
  - task: package
    file: commit-metrics/todo-block/deployment/tasks/build-java-function.yml
    params:
      function_name: commit-metrics
  - task: deploy
    file: commit-metrics/todo-block/deployment/tasks/deploy-function.yml
    params:
      function_name: commit-metrics
      app_binding: github-event-core
      aws_default_region: {{aws-region}}
      aws_access_key_id: {{aws-access-key-id}}
      aws_secret_access_key: {{aws-access-key-secret}}
      bucket_name: {{s3-bucket}}
      service_instance: {{pws-mysql-service}}
      service_key: {{pws-mysql-service-key}}
      api: {{pws-api}}
      username: {{pws-username}}
      password: {{pws-password}}
      organization: {{pws-org}}
      space: {{pws-space}}