---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: maven
    tag: alpine
inputs:
- name: service-core
outputs:
- name: artifact
run:
  path: sh
  args:
  - -exc
  - |
    cd service-core \
    && mvn clean package -DskipDockerBuild \
    && mv cqrs-service-block/service-core/target/service-core*.jar ../artifact/github-stream-core.jar
