
---
resources:
- name: service-core
  type: git
  source:
    uri: https://github.com/kbastani/service-block-samples
    branch: master
    paths:
    - ./cqrs-block/github-event-core
- name: project-created
  type: git
  source:
    uri: https://github.com/kbastani/service-block-samples
    branch: master
    paths:
    - ./cqrs-block/functions/project-created
- name: project-committed
  type: git
  source:
    uri: https://github.com/kbastani/service-block-samples
    branch: master
    paths:
    - ./cqrs-block/functions/project-committed
- name: tight-coupling-query
  type: git
  source:
    uri: https://github.com/kbastani/service-block-samples
    branch: master
    paths:
    - ./cqrs-block/functions/tight-coupling-query
jobs:
- name: cqrs-service-block-ci
  max_in_flight: 1
  plan:
  - get: service-core
    trigger: true
  - task: build
    file: service-core/cqrs-block/deployment/tasks/build-core.yml
  - task: deployment
    file: service-core/cqrs-block/deployment/tasks/deploy-core.yml
    params:
      path: artifact/github-event-core.jar
      current_app_name: github-event-core
      host: github-event-core
      domain: cfapps.io
      manifest: service-core/cqrs-block/github-event-core/manifest.yml
      api: {{pws-api}}
      username: {{pws-username}}
      password: {{pws-password}}
      organization: {{pws-org}}
      aws_access_key_id: {{aws-access-key-id}}
      aws_access_key_secret: {{aws-access-key-secret}}
      github_access_token: {{github-access-token}}
      space: {{pws-space}}
- name: project-created-ci
  max_in_flight: 1
  plan:
  - get: project-created
    trigger: true
  - task: prepare
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
        - name: project-created
      outputs:
        - name: functions
        - name: scripts
      run:
        path: sh
        args:
        - -exc
        - |
          cp -r project-created/cqrs-block/functions/* functions \
          && cp -r project-created/cqrs-block/deployment/scripts/* scripts
  - task: package
    file: project-created/cqrs-block/deployment/tasks/build-java-function.yml
    params:
      function_name: project-created
  - task: deploy
    file: project-created/cqrs-block/deployment/tasks/deploy-js-function.yml
    params:
      function_name: project-created
      app_binding: github-event-core
      aws_default_region: {{aws-region}}
      aws_access_key_id: {{aws-access-key-id}}
      aws_secret_access_key: {{aws-access-key-secret}}
      bucket_name: {{s3-bucket}}
      service_instance: {{pws-mysql-service}}
      service_key: {{pws-mysql-service-key}}
      api: {{pws-api}}
      username: {{pws-username}}
      password: {{pws-password}}
      organization: {{pws-org}}
      space: {{pws-space}}
- name: project-committed-ci
  max_in_flight: 1
  plan:
  - get: project-committed
    trigger: true
  - task: prepare
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
        - name: project-committed
      outputs:
        - name: functions
        - name: scripts
      run:
        path: sh
        args:
        - -exc
        - |
          cp -r project-committed/cqrs-block/functions/* functions \
          && cp -r project-committed/cqrs-block/deployment/scripts/* scripts
  - task: package
    file: project-committed/cqrs-block/deployment/tasks/build-java-function.yml
    params:
      function_name: project-committed
  - task: deploy
    file: project-committed/cqrs-block/deployment/tasks/deploy-js-function.yml
    params:
      function_name: project-committed
      app_binding: github-event-core
      aws_default_region: {{aws-region}}
      aws_access_key_id: {{aws-access-key-id}}
      aws_secret_access_key: {{aws-access-key-secret}}
      bucket_name: {{s3-bucket}}
      service_instance: {{pws-mysql-service}}
      service_key: {{pws-mysql-service-key}}
      api: {{pws-api}}
      username: {{pws-username}}
      password: {{pws-password}}
      organization: {{pws-org}}
      space: {{pws-space}}
- name: tight-coupling-query-ci
  max_in_flight: 1
  plan:
  - get: tight-coupling-query
    trigger: true
  - task: prepare
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
        - name: tight-coupling-query
      outputs:
        - name: functions
        - name: scripts
      run:
        path: sh
        args:
        - -exc
        - |
          cp -r tight-coupling-query/cqrs-block/functions/* functions \
          && cp -r tight-coupling-query/cqrs-block/deployment/scripts/* scripts
  - task: package
    file: tight-coupling-query/cqrs-block/deployment/tasks/build-java-function.yml
    params:
      function_name: tight-coupling-query
  - task: deploy
    file: tight-coupling-query/cqrs-block/deployment/tasks/deploy-js-function.yml
    params:
      function_name: tight-coupling-query
      app_binding: github-event-core
      aws_default_region: {{aws-region}}
      aws_access_key_id: {{aws-access-key-id}}
      aws_secret_access_key: {{aws-access-key-secret}}
      bucket_name: {{s3-bucket}}
      service_instance: {{pws-mysql-service}}
      service_key: {{pws-mysql-service-key}}
      api: {{pws-api}}
      username: {{pws-username}}
      password: {{pws-password}}
      organization: {{pws-org}}
      space: {{pws-space}}