
---
resources:
- name: service-core
  type: git
  source:
    uri: https://github.com/kbastani/service-block-samples
    branch: master
    paths:
    - ./cqrs/cqrs-service-core
- name: account-activated
  type: git
  source:
    uri: https://github.com/kbastani/service-block-samples
    branch: master
    paths:
    - ./cqrs/functions/account-activated
jobs:
- name: cqrs-service-block-ci
  max_in_flight: 1
  plan:
  - get: service-core
    trigger: true
  - task: build
    file: service-core/cqrs/deployment/tasks/build-core.yml
  - task: deployment
    file: service-core/cqrs/deployment/tasks/deploy-core.yml
    params:
      path: artifact/account-service-core.jar
      current_app_name: cqrs-service-block
      host: account-service-core
      domain: cfapps.io
      manifest: service-core/cqrs/cqrs-service-core/manifest.yml
      api: {{pws-api}}
      username: {{pws-username}}
      password: {{pws-password}}
      organization: {{pws-org}}
      aws_access_key_id: {{aws-access-key-id}}
      aws_access_key_secret: {{aws-access-key-secret}}
      space: {{pws-space}}
- name: account-activated-ci
  max_in_flight: 1
  plan:
  - get: account-activated
    trigger: true
  - task: prepare
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
        - name: account-activated
      outputs:
        - name: functions
        - name: scripts
      run:
        path: sh
        args:
        - -exc
        - |
          cp -r account-activated/cqrs/functions/* functions \
          && cp -r account-activated/cqrs/deployment/scripts/* scripts
  - task: package
    file: account-activated/cqrs/deployment/tasks/build-js-function.yml
    params:
      function_name: account-activated
  - task: deploy
    file: account-activated/cqrs/deployment/tasks/deploy-js-function.yml
    params:
      function_name: account-activated
      aws_default_region: {{aws-region}}
      aws_access_key_id: {{aws-access-key-id}}
      aws_secret_access_key: {{aws-access-key-secret}}
      bucket_name: {{s3-bucket}}
      service_instance: {{pws-mysql-service}}
      service_key: {{pws-mysql-service-key}}
      api: {{pws-api}}
      username: {{pws-username}}
      password: {{pws-password}}
      organization: {{pws-org}}
      space: {{pws-space}}
- name: account-suspended-ci
  max_in_flight: 1
  plan:
  - get: account-suspended
    trigger: true
  - task: prepare
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
        - name: account-suspended
      outputs:
        - name: functions
        - name: scripts
      run:
        path: sh
        args:
        - -exc
        - |
          cp -r account-suspended/cqrs/functions/* functions \
          && cp -r account-suspended/cqrs/deployment/scripts/* scripts
  - task: package
    file: account-suspended/cqrs/deployment/tasks/build-js-function.yml
    params:
      function_name: account-suspended
  - task: deploy
    file: account-suspended/cqrs/deployment/tasks/deploy-js-function.yml
    params:
      function_name: account-suspended
      aws_default_region: {{aws-region}}
      aws_access_key_id: {{aws-access-key-id}}
      aws_secret_access_key: {{aws-access-key-secret}}
      bucket_name: {{s3-bucket}}