---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: latest
inputs:
- name: function-package
run:
  path: ./function-package/deploy-function.sh
  args:
  - $bucket_name