---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: '3.4'
inputs:
- name: function-package
run:
  path: sh
  args:
  - -exc
  - |
    cd function-package \
    && ./deploy-function.sh $bucket_name