---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: latest
inputs:
- name: function-package
run:
  path: sh
  args:
  - sh ./function-package/deploy-function.sh $bucket_name