AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: project created handler
Resources:
  projectCreated:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: demo.functions.Handler
      Runtime: java8
      FunctionName: project-created
      CodeUri: ./project-created-1.0.0-SNAPSHOT-aws.jar
      Description: Responds to an project created event
      MemorySize: 1024
      Timeout: 30
      Role: 'arn:aws:iam::194021864310:role/service-role/public'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /projectCreated
            Method: ANY