
---
resources:
- name: source
  type: git
  source:
    uri: https://github.com/kbastani/service-block-samples
    branch: master
    paths:
    - ./basic-service-block
jobs:
- name: deploy
  max_in_flight: 1
  plan:
  - get: source
    trigger: true
  - task: build
    file: source/basic-service-block/deployment/tasks/build.yml
  - task: deployment
    file: source/basic-service-block/deployment/tasks/deploy.yml
    params:
      path: artifact/account-service-core.jar
      current_app_name: account-service-core
      host: account-service-core
      domain: cfapps.io
      manifest: source/basic-service-block/service-core/manifest.yml
      api: {{pws-api}}
      username: {{pws-username}}
      password: {{pws-password}}
      organization: {{pws-org}}
      aws_access_key_id: {{aws-access-key-id}}
      aws_access_key_secret: {{aws-access-key-secret}}
      space: {{pws-space}}
