
---
resources:
- name: service-core
  type: git
  source:
    uri: https://github.com/kbastani/service-block-samples
    branch: master
    paths:
    - ./basic-service-block/service-core
- name: account-activated
  type: git
  source:
    uri: https://github.com/kbastani/service-block-samples
    branch: master
    paths:
    - ./basic-service-block/functions/account-activated
    - ./basic-service-block/deployment/build-js-function.yml
    - ./basic-service-block/deployment/deploy-js-function.yml
jobs:
- name: service-core-ci
  max_in_flight: 1
  plan:
  - get: service-core
    trigger: true
  - task: build
    file: service-core/basic-service-block/deployment/tasks/build-core.yml
  - task: deployment
    file: service-core/basic-service-block/deployment/tasks/deploy-core.yml
    params:
      path: artifact/account-service-core.jar
      current_app_name: account-service-core
      host: account-service-core
      domain: cfapps.io
      manifest: service-core/basic-service-block/service-core/manifest.yml
      api: {{pws-api}}
      username: {{pws-username}}
      password: {{pws-password}}
      organization: {{pws-org}}
      aws_access_key_id: {{aws-access-key-id}}
      aws_access_key_secret: {{aws-access-key-secret}}
      space: {{pws-space}}
- name: account-activated-ci
  max_in_flight: 1
  plan:
  - get: account-activated
    trigger: true
  - task: prepare
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
        - name: account-activated
      outputs:
        - name: functions
        - name: scripts
      run:
        path: sh
        args:
        - -exc
        - |
          cp -r account-activated/basic-service-block/functions/* functions \
          && cp account-activated/basic-service-block/deployment/scripts/* scripts
  - task: package
    file: account-activated/basic-service-block/deployment/tasks/build-js-function.yml
    params:
      function_name: account-activated
  - task: deploy
    file: account-activated/basic-service-block/deployment/tasks/deploy-js-function.yml
    params:
      function_name: account-activated
      aws_default_region: {{aws-region}}
      aws_access_key_id: {{aws-access-key-id}}
      aws_secret_access_key: {{aws-access-key-secret}}
      s3_bucket: {{s3-bucket}}